@VueWithASP.Server_HostAddress = http://localhost:5098

POST {{VueWithASP.Server_HostAddress}}/login/
Accept: application/json

GET {{VueWithASP.Server_HostAddress}}/login/
Accept: application/json


###
